# Jekyll configuration

name: Craft's Cursed Code
description: Software Engineering for fun

# Url is currently only used only for the RSS feed in feed.xml
url: http://craftspider.github.io
#url: http://localhost:4000

plugins: ["jekyll-paginate-v2"]

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: ''

author: CraftSpider
copyright: 2021

share:
  facebook: false
  twitter: true
  gplus: false
  linkedin: true
  pinterest: false
  email: true

social:
  github: craftspider
  stackoverflow:
  twitter: RuneTynan
  linkedin:
  instagram:
  lastfm:
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-214729556-1
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: craftspider
comments: false

permalink: /:year/:month/:title/

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
pagination:
  enabled: true
  per_page: 5
  permalink: /page:num/
  sort_reverse: true

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE', 'jekyll-clean-dark.gemspec']
